routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'IndexController@login')->name('login.form');
Route::get('/keluar', 'IndexController@logouts')->name('logout.form');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('/category', 'CategoryController');
Route::resource('/user', 'UserController');
Route::resource('/product', 'ProductController');
Route::get('/transaksi', 'TransaksiController@index')->name('transaksi.index');
Route::get('/transaksi/create', 'TransaksiController@create')->name('transaksi.create');
Route::post('/post/transaksi', 'TransaksiController@store')->name('transaksi.post');
Route::post('/search/producr', 'TransaksiController@searchProduct')->name('search.create');

resources/views/layout/flash-message.blade.php
@if ($message = Session::get('success'))
<div class="alert alert-success alert-block">
	<button type="button" class="close" data-dismiss="alert">×</button>	
        <strong>{{ $message }}</strong>
</div>
@endif


@if ($message = Session::get('error'))
<div class="alert alert-danger alert-block">
	<button type="button" class="close" data-dismiss="alert">×</button>	
        <strong>{{ $message }}</strong>
</div>
@endif


@if ($message = Session::get('warning'))
<div class="alert alert-warning alert-block">
	<button type="button" class="close" data-dismiss="alert">×</button>	
	<strong>{{ $message }}</strong>
</div>
@endif


@if ($message = Session::get('info'))
<div class="alert alert-info alert-block">
	<button type="button" class="close" data-dismiss="alert">×</button>	
	<strong>{{ $message }}</strong>
</div>
@endif


@if ($errors->any())
<div class="alert alert-danger">
	<button type="button" class="close" data-dismiss="alert">×</button>	
	Please check the form below for errors
</div>
@endif

resources/views/layout/footer.blade.php
 <!-- Footer -->
 <footer class="footer">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                © <?php echo date("Y") ?> Test Code 
            </div>
        </div>
    </div>
</footer>
<!-- End Footer -->


<!-- jQuery  -->
<script src="{{asset('assetsnew/js/jquery.min.js')}}"></script>
<script src="{{asset('assetsnew/js/popper.min.js')}}"></script>
<script src="{{asset('assetsnew/js/bootstrap.min.js')}}"></script>


<!-- Plugins js -->
<script src="{{asset('assetsnew/plugins/bootstrap-colorpicker/js/bootstrap-colorpicker.min.js')}}"></script>
<script src="{{asset('assetsnew/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js')}}"></script>
<script src="{{asset('assetsnew/plugins/select2/js/select2.min.js')}}" type="text/javascript"></script>
<script src="{{asset('assetsnew/plugins/bootstrap-maxlength/bootstrap-maxlength.min.js')}}" type="text/javascript"></script>
<script src="{{asset('assetsnew/plugins/bootstrap-touchspin/js/jquery.bootstrap-touchspin.min.js')}}" type="text/javascript"></script>
<script src="{{asset('assetsnew/plugins/sweet-alert2/sweetalert2.min.js')}}" type="text/javascript"></script>

<script src="{{asset('assetsnew/pages/form-advanced.js')}}"></script>

<script src='https://cdn.rawgit.com/admsev/jquery-play-sound/master/jquery.playSound.js'></script>

<!-- App js -->
<script src="{{asset('assetsnew/js/app.js')}}"></script>

<script src="{{asset('assetsnew/plugins/alertify/js/alertify.js')}}"></script>
<script src="{{asset('assetsnew/pages/alertify-init.js')}}"></script>
<script src="https://js.pusher.com/6.0/pusher.min.js"></script>

resources/views/layout/head.blade.php
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
        <title>Test Code</title>
        <meta content="Admin Dashboard" name="description" />
        <meta content="Themesbrand" name="author" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />

        <!-- App Icons -->
        <link rel="shortcut icon" href="{{asset('assetsnew/images/logo-dark-large.png')}}">

        <!-- App css -->
        <link href="{{asset('assetsnew/css/bootstrap.min.css')}}" rel="stylesheet" type="text/css" />
        <link href="{{asset('assetsnew/css/icons.css')}}" rel="stylesheet" type="text/css" />
        <link href="{{asset('assetsnew/css/style.css')}}" rel="stylesheet" type="text/css" />
        <link href="{{asset('assetsnew/plugins/sweet-alert2/sweetalert2.min.css')}}" rel="stylesheet" />
        <!--pluggin CSS -->
        <link href="{{asset('assetsnew/plugins/select2/css/select2.min.css')}}" rel="stylesheet" type="text/css" />
        <link href="{{asset('assetsnew/plugins/bootstrap-touchspin/css/jquery.bootstrap-touchspin.min.css')}}" rel="stylesheet" />
     

resources/views/layout/navbar.blade.php
    <!-- Loader -->
    <div id="preloader"><div id="status"><div class="spinner"></div></div></div>

    <div class="header-bg">
        <!-- Navigation Bar-->
        <header id="topnav">
            <div class="topbar-main">
                <div class="container-fluid">

                    <!-- Logo container-->
                    <div class="logo">
                        <!-- Text Logo -->
                        <!-- Image Logo -->
                        <a href="#" class="logo">
                            test Code
                        </a>

                    </div>
                    <!-- End Logo container-->


                    <div class="menu-extras topbar-custom">

                        <ul class="list-inline float-right mb-0">
                            
                            <!-- notification-->
                        <?php $user=Auth::user()->is_admin?>
                            @if ($user == 2)
                                <li class="list-inline-item dropdown notification-list">
                                <a class="nav-link dropdown-toggle arrow-none waves-effect" data-toggle="dropdown" href="#" role="button"
                                aria-haspopup="false" aria-expanded="false">
                                    <i class="ti-bell noti-icon"></i>
                                    <span class="badge badge-info badge-pill noti-icon-badge"><div class="notif"></div></span>
                                </a>
                                <div class="dropdown-menu dropdown-menu-right dropdown-arrow dropdown-menu-lg">
                                    <!-- item-->
                                    <div class="dropdown-item noti-title">
                                        <a href="{{ route('service.in')}}">Notification (<span class="notif"></span>) </a>
                                    </div>

                                    <!-- item-->
                                    <div class="notifikasiviewteknisi"></div>

                                </div>
                            </li>
                            @elseif($user == 1)
                            @else
                                <li class="list-inline-item dropdown notification-list">
                                <a class="nav-link dropdown-toggle arrow-none waves-effect" data-toggle="dropdown" href="#" role="button"
                                aria-haspopup="false" aria-expanded="false">
                                    <i class="ti-bell noti-icon"></i>
                                    <span class="badge badge-info badge-pill noti-icon-badge"><div class="notifs"></div></span>
                                </a>
                                <div class="dropdown-menu dropdown-menu-right dropdown-arrow dropdown-menu-lg">
                                    <!-- item-->
                                    <div class="dropdown-item noti-title">
                                        <a href="{{ route('home')}}">Notification (<span class="notifs"></span>) </a>
                                    </div>

                                    <!-- item-->
                                    <div class="notifikasiview"></div>

                                </div>
                            </li>
                            @endif
                            <!-- User-->
                            <li class="list-inline-item dropdown notification-list">
                                <a class="nav-link dropdown-toggle arrow-none waves-effect nav-user" data-toggle="dropdown" href="#" role="button"
                                aria-haspopup="false" aria-expanded="false">
                                    @if(empty($users))
                                    <img src="{{asset('assetsnew/images/users/images.jfif')}}" alt="user" class="rounded-circle">
                                    @else
                                    <img src="{{ asset('/images/'.$users[0]->image) }}" alt="user" class="rounded-circle">
                                    @endif
                                    <span class="ml-1">{{ $user=Auth::user()->name}}. <i class="mdi mdi-chevron-down"></i> </span>
                                </a>
                                <div class="dropdown-menu dropdown-menu-right profile-dropdown ">
                                    <a class="dropdown-item" href=""><i class="dripicons-user text-muted"></i> Profile</a>
                                    <a class="dropdown-item" href=""><i class="dripicons-gear text-muted"></i> Settings</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" href="{{ route('logout.form')}}"><i class="dripicons-exit text-muted"></i> Logout</a>
                                </div>
                            </li>
                            <li class="menu-item list-inline-item">
                                <!-- Mobile menu toggle-->
                                <a class="navbar-toggle nav-link">
                                    <div class="lines">
                                        <span></span>
                                        <span></span>
                                        <span></span>
                                    </div>
                                </a>
                                <!-- End mobile menu toggle-->
                            </li>

                        </ul>
                    </div>
                    <!-- end menu-extras -->

                    <div class="clearfix"></div>

                </div> <!-- end container -->
            </div>
            <!-- end topbar-main -->

            <!-- MENU Start -->
            <div class="navbar-custom">
                <div class="container-fluid">
                    <div id="navigation">
                        <!-- Navigation Menu-->
                        <ul class="navigation-menu">
                                                  
                            <li class="has-submenu">
                                <a href="{{Route('home')}}"><i class="dripicons-device-desktop"></i>Dashboard</a>
                            </li>
                            <li class="has-submenu">
                                <a href="{{route('category.index')}}"><i class="dripicons-device-desktop"></i>Category</a>
                            </li>
                                                  
                            <li class="has-submenu">
                                <a href="{{route('user.index')}}"><i class="dripicons-device-desktop"></i>User</a>
                            </li>
                        
                            <li class="has-submenu">
                                <a href="{{route('product.index')}}"><i class="dripicons-device-desktop"></i>product</a>
                            </li>
                                                  
                            <li class="has-submenu">
                                <a href="{{route('transaksi.index')}}"><i class="dripicons-device-desktop"></i>Transaksi</a>
                            </li>
                        </ul>
                        <!-- End navigation menu -->
                    </div> <!-- end #navigation -->
                </div> <!-- end container -->
            </div> <!-- end navbar-custom -->
        </header>
        <!-- End Navigation Bar-->

resources/views/layout/script.blade.php
{{-- <?php $user=Auth::user()->is_admin?>
    @if ($user == 2)
    <script>
        $(document).ready(function () {
                var ids=0;
                $.ajax({
                url :'../notif/'+ ids,
                cache: false,
                success:function(data)
                    {
                        object = JSON.parse(data);
                        $('.notif').text(object[0].notif);
                        this.timer =  $('.notif').text(object[0].notif);
                        this.runTimer = setInterval(() => {
                            this.timer.innerHTML = ++this.currTimer;
                        },1000);
                    }
                })
            });
            function testAjax() {
                var ids=0;
                $.ajax({
                url :'../notif/' + ids,
                cache: false,
                success:function(data)
                    {
                        object = JSON.parse(data);
                        $('.notif').text(object[0].notif);
                        this.timer =  $('.notif').text(object[0].notif);
                        this.runTimer = setInterval(() => {
                            this.timer.innerHTML = ++this.currTimer;
                        },1000);
                    }
                })
            }
            setInterval(function(){
                testAjax();;
            }, 5000);
    </script>
    @elseif($user == 0)
    <script>
        $(document).ready(function () {
                var ids=3;
                $.ajax({
                url :'notif/' + ids,
                cache: false,
                success:function(data)
                    {
                        object = JSON.parse(data);
                        
                        $('.notifs').text(object[0].notif);
                        
                    }
                })
            });
            function testAjax() {
                var ids=3;
                $.ajax({
                url :'notif/' + ids,
                cache: false,
                success:function(data)
                    {
                        object = JSON.parse(data);
                        $('.notifs').text(object[0].notif);
                    }
                })
            }
            setInterval(function(){
                testAjax();;
            }, 5000);
    </script>
    
    @else
        
    @endif --}}